print("Ordene las ecuaciones y luego ingrese los coeficientes de forma ordenada")
a1=float(input("a1="))
b1=float(input("b1="))
c1=float(input("c1="))
a2=float(input("a2="))
b2=float(input("b2="))
c2=float(input("c2="))
